### ISSUE TITLE
找不到资源

### ISSUE THREAD

**Issue by fupan1018** [imxiaoer/ElementUIAdmin#1]
大佬，我把你的项目拉取下拉，打包后找不到资源，这是为什么
![8b90053438342440fc34ab412a29339](https://user-images.githubusercontent.com/16321092/99036788-4add5d00-25bd-11eb-8f71-f44bbe70542a.png)

**Comment by icoomn** [comment]
执行 npm run serve 可以正常运行吗？
怎么是直接访问的物理路径？打包后要挂载在服务器上访问，如 IIS，Apache，Live Server 等。

**Comment by fupan1018** [comment]
npm run serve 可以，我放在iis下的

**Comment by fupan1018** [comment]
我把路由的mode改成哈希值就可以了，如果用history就不行

**Comment by icoomn** [comment]
iis服务器下使用history模式，需要做配置的。需要配置路由重写 Rewrite 规则，你百度找下相关文章就知道了

**Comment by fupan1018** [comment]
好的谢谢
