### ISSUE TITLE
您好，能给个数据接口api吗？

### ISSUE THREAD

**Issue by wxyDL** [imxiaoer/ElementUIAdmin#2]

**Comment by icoomn** [comment]
都是模拟的假数据，具体请看src下的mock.js

**Comment by wxyDL** [comment]
谢谢------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;前端小玖&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年1月27日(星期三) 上午10:52
收件人:&nbsp;&quot;imxiaoer/ElementUIAdmin&quot;<ElementUIAdmin@noreply.github.com&gt;;
抄送:&nbsp;&quot;wxyDL&quot;<1726010671@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [imxiaoer/ElementUIAdmin] 您好，能给个数据接口api吗？ (#2)
